### ISSUE TITLE
black scope on zoom 

### ISSUE THREAD

**Issue by RisenBlood** [Hydroflame522/StateFarmClient#177]
Scope is black when zoomed in with sniper weapons. 
![Screenshot 2024-06-16 150352](https://github.com/Hydroflame522/StateFarmClient/assets/167650193/559a65ba-6252-4988-a586-e8d9af913342)

not present when script is installed. Tried to reset script and still no change.

**Comment by onlypuppy7** [comment]
fixed in pre75
