### ISSUE TITLE
ShellShockers Script Adblock

### ISSUE THREAD

**Issue by WisplessWispless** [Hydroflame522/StateFarmClient#181]
Hey Hydroflame!

I was playing with your script, which works amazingly well, but I kept noticing the extra 5 second ad delay I would get. Is there a way to remove the adblock portion of your script to avoid this 5 second delay? I would be happy to watch the ads, or isntall my own private ad blocker.

Thanks!

**Comment by OakSwingZZZ** [comment]
Turn on the Adblock feature of the script and reload.
