### ISSUE TITLE
wont inject

### ISSUE THREAD

**Issue by KillzTheSpy2** [Hydroflame522/StateFarmClient#182]
it just wont inject. There is an inject error in the console which reads:
`Replacement failed! Attempted to replace /tp-/g with: `
Im assuming it tried to replace it with an non-existent file or you just forgot to put the filename there.

**Comment by KillzTheSpy2** [comment]
I found in the script itself where it replaces it, its line 4690, and its empty.
`modifyJS(/tp-/g, '');`
is it supposed to be?

**Comment by VillainsRule** [comment]
that's an error that is supposed to happen, if you see that, it's good
we don't provide support here, join the discord
https://dsc.gg/sfnetwork
