### ISSUE TITLE
My Shell Shockers (main) screen freezes

### ISSUE THREAD

**Issue by Amaan913** [Hydroflame522/StateFarmClient#187]
There are two screens opened one is the bot and second is mine "main shell shocker" screen after the bot dies and when it respawns my screen freezes

https://github.com/user-attachments/assets/ee958264-1774-404e-9c20-4398141fdad7
![image](https://github.com/user-attachments/assets/3f842b5f-de95-41be-9046-23fee3c02685)   SEE THE IMAGE, I NEEED to refresh after my bot respawns as my main shell shockers windows freezes

Please Help me out....

**Comment by Amaan913** [comment]
> any errors in the main window's console?

I dont Think so.... How do i Check it ? My Main Shell Shocker's Screen freezes when the bot in the left side window clicks respawn 


See the picture in my post there u can see the left screen bot window, it works fine but my main screen freezes.

**Comment by Hydroflame522** [comment]
ask for support in the discord, we dont check this often

**Comment by Hydroflame522** [comment]
nonreproducable, didnt come back up as an issue
