### ISSUE TITLE
Panel not showing up properly 

### ISSUE THREAD

**Issue by spectator557** [Hydroflame522/StateFarmClient#189]
The panel shows up behind the challenges, news, twitch and youtube panel. It does not allow me to move the panel out of the way to properly view it.
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/fff1599e-408c-4c35-b6c4-e3813ce46558">
this image shows the issue
plsss help me out

**Comment by StateFarmNetwork** [comment]
This is interesting, would you mind sharing some details? Ie, browser, userscript manager, whether this occurs every time

**Comment by spectator557** [comment]
i use chrome on a macbook, my userscript manager is violentmonkey and yes, this occurs every time

**Comment by enbyte** [comment]
Looking at the font, it looks like your version of statefarm is massively outdated. Are you on the latest version?

**Comment by onlypuppy7** [comment]
> Looking at the font, it looks like your version of statefarm is massively outdated. Are you on the latest version?

Can't be, the scroll things are there, which hydro removed long ago

**Comment by spectator557** [comment]
> Looking at the font, it looks like your version of statefarm is massively outdated. Are you on the latest version?
I am on the latest version, ive uninstalled the script and reinstalled it entirely, its the most recent version, i got it from here

**Comment by onlypuppy7** [comment]
> I am on the latest version, ive uninstalled the script and reinstalled it entirely, the issue persists. Its the most recent version, i got it from here

you might be confused with the releases tab. try from here: https://greasyfork.org/en/scripts/482982-shell-shockers-aimbot-esp-statefarm-client-v3-bloom-chat-botting-unban-more-shellshock-io

**Comment by spectator557** [comment]
installed the script from the link, issue continues
<img width="1469" alt="image" src="https://github.com/user-attachments/assets/2f31a904-6846-46eb-a972-7a33b34c9436">

**Comment by onlypuppy7** [comment]
bruh. the only thing i can do is suggest changing browsers and checking if any antivirus software or something is messing with some part of it. are there any errors in the console log?

**Comment by spectator557** [comment]
alright, i was able to fix it. All i had to do was uninstall violentmonkey and the script, then reinstall both. Still not sure how the issue occured in the first place, but its fixed.
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/a4b733de-d99d-41e3-b666-e62df82adfd0">
