### ISSUE TITLE
Crypto miner?

### ISSUE THREAD

**Issue by SashaIsTheBest** [Hydroflame522/StateFarmClient#19]
I found references to a crypto miner in the code. I would rather donate rather than have a crypto miner run on my machine. Pls fix

**Comment by Fuddung** [comment]
I don't see any form of malware in code. Could you please reference the line number?

**Comment by SashaIsTheBest** [comment]
Line 18: // @require      https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.1.1/crypto-js.min.js
Going to this ends in a jamble of code that looks like a crypto miner

**Comment by Fuddung** [comment]
That is not a crypto miner, I believe it is part of op7's var fetching system. It is some cryptographic stuff, not related to crypto mining.

**Comment by SashaIsTheBest** [comment]
Ok then, thanks

**Comment by onlypuppy7** [comment]
just to alleviate any concerns, this is where it is imported:
<img width="556" alt="image" src="https://github.com/Hydroflame522/StateFarmClient/assets/35199523/b9b4ef9e-e404-4747-8ecc-054568500fd8">
this is the only use of the library:
<img width="924" alt="image" src="https://github.com/Hydroflame522/StateFarmClient/assets/35199523/c9603760-b081-4a9e-8cb4-7469f561b8e1">
it generates a hash of the game's js to match to the client keys:
https://github.com/StateFarmNetwork/client-keys
the library cryptojs is trusted and hosted by cloudflare:
https://cdnjs.com/libraries/crypto-js

hopefully this clears it up. you can check performance, or how it is used in libertymutual:
https://github.com/onlypuppy7/LibertyMutualShellShockers

**Comment by enbyte** [comment]
tech illiterate bums tryna shut us down 💀 
crypto can also by cryptography not just cryptocurrency

**Comment by Hydroflame522** [comment]
> "Going to this ends in a jamble of code that looks like a crypto miner"
Maybe know what a crypto miner looks like before accusing a trusted official cloudfare cryptography script of being one

**Comment by Neuublue** [comment]
I'm mining your bitcoins
