### ISSUE TITLE
User Script not working 

### ISSUE THREAD

**Issue by Dhruv594** [Hydroflame522/StateFarmClient#199]
![Screenshot 2024-10-08 173503](https://github.com/user-attachments/assets/8e067ac1-3c16-4a8f-934d-3cdb931fe23e)

It's not letting me play

**Comment by hydroflame521** [comment]
from the screen to the ring to the pen to the king

**Comment by hydroflame521** [comment]
turn off camwip or whatever its called

**Comment by onlypuppy7** [comment]
> turn off camwip or whatever its called

it'll be finished soon

**Comment by Dhruv594** [comment]
I have CamWIP off and it's still not working
