### ISSUE TITLE
Additional aimbot setting

### ISSUE THREAD

**Issue by i0Z3R0** [Hydroflame522/StateFarmClient#204]
Currently, there's nearest and where you're aiming. A third option or rather, a toggle to lock onto whoever is not behind a wall automatically (prioritize visible targets) Because someone could come out of nowhere and it takes a second to change the aimbot to nearest, then aim towards that person when you see them on the ESP.

**Comment by VillainsRule** [comment]
read the client menu lmao, this is implemented

**Comment by Hydroflame522** [comment]
los exists
