### ISSUE TITLE
No Wait To Rejoin [enhancement]

### ISSUE THREAD

**Issue by 22yeets22** [Hydroflame522/StateFarmClient#32]
I know it is possible to skip the waiting for 5 seconds before being able to rejoin in Shell shockers.
Used to work: https://greasyfork.org/en/scripts/448598-shellshock-io-remove-adblocker-messages-respawn-timer/code

**Comment by 22yeets22** [comment]
wdym

**Comment by Hydroflame522** [comment]
It's server based bro, modifying it clientside will have no effect.

Don't open issues on the github for random suggestions (they are meant for issues); if you have suggestions, there is a forum channel in our discord server.

**Comment by 22yeets22** [comment]
the script did work tho

**Comment by Fuddung** [comment]
doesn't work anymore

**Comment by Fuddung** [comment]
I have used this script before when it worked, it removes the timer but the game still won't spawn you in until the timer is up, rendering it useless.

**Comment by 22yeets22** [comment]
> I have used this script before when it worked, it removes the timer but the game still won't spawn you in until the timer is up, rendering it useless.

For me it worked, the GUI disappeared, you waited around 2 seconds instead of the 5, then loaded in

**Comment by Fuddung** [comment]
that's because it takes time for the UI to appear after death

**Comment by Fuddung** [comment]
totalling at the normal time

**Comment by Fuddung** [comment]
if you have suggestions or inquiries, maybe join our discord server
https://discord.gg/FkAnRJ3Hw3
