### ISSUE TITLE
Wont inject

### ISSUE THREAD

**Issue by King7164** [Hydroflame522/StateFarmClient#8]
Downloaded newest version 3.3.3-pre23 but it says it is outdated, whats happening?

**Comment by enbyte** [comment]
We're working on a fix; shell updated with some new obfuscation features that mess up the script.

**Comment by OakSwingZZZ** [comment]
Do you need any errors from the console?

**Comment by enbyte** [comment]
Nope, we got it. Thanks though.

**Comment by King7164** [comment]
> We're working on a fix; shell updated with some new obfuscation features that mess up the script.

Ok thanks for the response

**Comment by onlypuppy7** [comment]
it's fixed guys
