### ISSUE TITLE
Currently idk why stuck in loading screen try to reload it multiple times, did one time but renders nothing and aimbot not working

### ISSUE THREAD

**Issue by YikNYak** [Hydroflame522/StateFarmClient#9]
Currently idk why stuck in loading screen try to reload it multiple times, did one time but renders nothing and aimbot not working

**Comment by King7164** [comment]
yea i have the same thing lmao

**Comment by King7164** [comment]
Bro i j got banned i really need it back :(

**Comment by 2013hi** [comment]
i feel bad

**Comment by 2013hi** [comment]
PLS FIX ONLY PUPPY 7
